processus:
  train_model: False
  test_model: True
  use_model: False
train_params:
  CV: 
  algos:
  mode: 
  corpus_path: 
  model_path: 
test_params:
  models: 
    - ./models/deft2011_train_ngramChar_abs_1,1_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,2_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,3_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,4_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,5_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,6_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,7_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,8_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_1,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,2_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,3_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,4_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,5_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,6_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,7_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,8_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_2,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_3,3_RF100.model
    - ./models/deft2011_train_ngramChar_abs_3,4_RF100.model
    - ./models/deft2011_train_ngramChar_abs_3,5_RF100.model
    - ./models/deft2011_train_ngramChar_abs_3,6_RF100.model
    - ./models/deft2011_train_ngramChar_abs_3,7_RF100.model
    - ./models/deft2011_train_ngramChar_abs_3,8_RF100.model
    - ./models/deft2011_train_ngramChar_abs_3,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_3,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_4,4_RF100.model
    - ./models/deft2011_train_ngramChar_abs_4,5_RF100.model
    - ./models/deft2011_train_ngramChar_abs_4,6_RF100.model
    - ./models/deft2011_train_ngramChar_abs_4,7_RF100.model
    - ./models/deft2011_train_ngramChar_abs_4,8_RF100.model
    - ./models/deft2011_train_ngramChar_abs_4,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_4,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_5,5_RF100.model
    - ./models/deft2011_train_ngramChar_abs_5,6_RF100.model
    - ./models/deft2011_train_ngramChar_abs_5,7_RF100.model
    - ./models/deft2011_train_ngramChar_abs_5,8_RF100.model
    - ./models/deft2011_train_ngramChar_abs_5,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_5,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_6,6_RF100.model
    - ./models/deft2011_train_ngramChar_abs_6,7_RF100.model
    - ./models/deft2011_train_ngramChar_abs_6,8_RF100.model
    - ./models/deft2011_train_ngramChar_abs_6,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_6,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_7,7_RF100.model
    - ./models/deft2011_train_ngramChar_abs_7,8_RF100.model
    - ./models/deft2011_train_ngramChar_abs_7,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_7,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_8,8_RF100.model
    - ./models/deft2011_train_ngramChar_abs_8,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_8,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_9,9_RF100.model
    - ./models/deft2011_train_ngramChar_abs_9,10_RF100.model
    - ./models/deft2011_train_ngramChar_abs_10,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,1_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,2_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,3_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,4_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,5_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,6_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,7_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,8_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_1,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,2_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,3_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,4_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,5_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,6_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,7_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,8_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_2,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_3,3_RF100.model
    - ./models/deft2011_train_ngramChar_rel_3,4_RF100.model
    - ./models/deft2011_train_ngramChar_rel_3,5_RF100.model
    - ./models/deft2011_train_ngramChar_rel_3,6_RF100.model
    - ./models/deft2011_train_ngramChar_rel_3,7_RF100.model
    - ./models/deft2011_train_ngramChar_rel_3,8_RF100.model
    - ./models/deft2011_train_ngramChar_rel_3,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_3,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_4,4_RF100.model
    - ./models/deft2011_train_ngramChar_rel_4,5_RF100.model
    - ./models/deft2011_train_ngramChar_rel_4,6_RF100.model
    - ./models/deft2011_train_ngramChar_rel_4,7_RF100.model
    - ./models/deft2011_train_ngramChar_rel_4,8_RF100.model
    - ./models/deft2011_train_ngramChar_rel_4,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_4,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_5,5_RF100.model
    - ./models/deft2011_train_ngramChar_rel_5,6_RF100.model
    - ./models/deft2011_train_ngramChar_rel_5,7_RF100.model
    - ./models/deft2011_train_ngramChar_rel_5,8_RF100.model
    - ./models/deft2011_train_ngramChar_rel_5,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_5,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_6,6_RF100.model
    - ./models/deft2011_train_ngramChar_rel_6,7_RF100.model
    - ./models/deft2011_train_ngramChar_rel_6,8_RF100.model
    - ./models/deft2011_train_ngramChar_rel_6,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_6,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_7,7_RF100.model
    - ./models/deft2011_train_ngramChar_rel_7,8_RF100.model
    - ./models/deft2011_train_ngramChar_rel_7,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_7,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_8,8_RF100.model
    - ./models/deft2011_train_ngramChar_rel_8,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_8,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_9,9_RF100.model
    - ./models/deft2011_train_ngramChar_rel_9,10_RF100.model
    - ./models/deft2011_train_ngramChar_rel_10,10_RF100.model
  corpus_ref_path: ./corpora/deft2011_test.json
use_model_params:
  mode: 
  model: 
  corpus_unLabelled_path:
  corpus_labelled_path: 